twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        aside_menu: '@App\Service\AsideMenuService'

when@test:
    twig:
        strict_variables: true
